// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmJkH1doz9zjeOyM63Pxf0pCDVgF58Bjc',
    appId: '1:923083136188:web:008e37b3537e83f25744b9',
    messagingSenderId: '923083136188',
    projectId: 'life-link-86ed1',
    authDomain: 'life-link-86ed1.firebaseapp.com',
    storageBucket: 'life-link-86ed1.appspot.com',
    measurementId: 'G-WNHVC12TX2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-fliaPgnwoibiHG4ddCMInCLZL3KibUc',
    appId: '1:923083136188:android:062e4a6892ead0c95744b9',
    messagingSenderId: '923083136188',
    projectId: 'life-link-86ed1',
    storageBucket: 'life-link-86ed1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaI6N1BPV8npLZaLhF2MCsKVNc37ML7r0',
    appId: '1:923083136188:ios:40727d2d15ff95a35744b9',
    messagingSenderId: '923083136188',
    projectId: 'life-link-86ed1',
    storageBucket: 'life-link-86ed1.appspot.com',
    iosBundleId: 'com.example.flutterInterviewTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaI6N1BPV8npLZaLhF2MCsKVNc37ML7r0',
    appId: '1:923083136188:ios:40727d2d15ff95a35744b9',
    messagingSenderId: '923083136188',
    projectId: 'life-link-86ed1',
    storageBucket: 'life-link-86ed1.appspot.com',
    iosBundleId: 'com.example.flutterInterviewTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmJkH1doz9zjeOyM63Pxf0pCDVgF58Bjc',
    appId: '1:923083136188:web:3774b890976725b15744b9',
    messagingSenderId: '923083136188',
    projectId: 'life-link-86ed1',
    authDomain: 'life-link-86ed1.firebaseapp.com',
    storageBucket: 'life-link-86ed1.appspot.com',
    measurementId: 'G-5T4YS52CSX',
  );

}